### ISSUE TITLE
Fill support

### ISSUE THREAD

**Issue by obibring** [ianmiller347/feather-icons-react#10]
Hey there, would you consider adding support for the `fill` prop? I'd like to show icons like hearts and bookmarks as filled once users have interacted with them. The change looks trivial and I'd be happy to issue a pull request.

Thanks!

**Comment by ianmiller347** [comment]
@obibring i'm more than happy to accept a pull request. Supporting the fill prop makes plenty sense

**Comment by ianmiller347** [comment]
@obibring i believe it should be as simple as changing this line: https://github.com/ianmiller347/feather-icons-react/blob/master/src/index.js#L14 to be `fill={props.fill || 'none'}` unless you also want to name the prop. Let me know if I can help, I should have more time to look at it this weekend.

**Comment by ianmiller347** [comment]
resolved with #15
