### ISSUE TITLE
Missing some icons available on feathericons.com

### ISSUE THREAD

**Issue by tomvrampio** [ianmiller347/feather-icons-react#11]
In particular I found "smile", "meh" and "frown" were missing

**Comment by ianmiller347** [comment]
@tomvrampio I can make a pull request this week maybe next to update. All that needs to be done is running the build on feather and then copying the resulting JSON of the icons over to this repo. I am open to pull requests if you have time!

**Comment by tomvrampio** [comment]
I don't know the full list of icons that's missing but I've forked and made a pull request just for those 3 icons - I hope this is ok :)

**Comment by tomvrampio** [comment]
Hmm, the NPM package reports as v0.4.0, but on install the new icons are missing - runkit confirms. All is well on GitHub though - can you shed any light?

**Comment by ianmiller347** [comment]
Hey i've fixed the issue with version 0.4.1 and confirmed it working after
publish.

I now realize that I never updated the build script to automatically copy
the json file to the build path (which is where NPM uses it).
