### ISSUE TITLE
https://github.com/ianmiller347/feather-icons-react/pulls

### ISSUE THREAD

**Issue by marquez138** [ianmiller347/feather-icons-react#8]
Sorry newbie question but how can change the colors for the icons?

**Comment by ianmiller347** [comment]
@marquez138 the color is defaulted to be the same color as the text in its container. If you want to control the color, you can set `color: rgb(x,x,x)` or any color format of choice on the parent div or even on the icon directly.

example on icon directly:
```
<Icon icon="x" className="color-red" />
```

example with container div:
```
// index.js
render() {
  return (
    <div className="color-red">
      <Icon icon="x" />
    </div>
  );
}
```
and then in your style file:
```
// style.css
.color-red {
  color: red;
}
```
